const PhotographersUserRoutes = require('./Photographers/user/user.route.js');
const DesignerUserRoutes = require('./Designer/user/user.route.js');
const roleRoutes = require('./Master/role/role.route.js');
const stateRoutes = require('./Master/state/state.route.js');
const cityRoutes = require('./Master/city/city.route.js');
const countryRoutes = require('./Master/country/country.route.js');
const socialMediaRoutes = require('./Master/social.media/social.media.route.js');
const notificationsRoutes = require('./Master/notifications/notifications.route.js');
const notificationMapUserRoutes = require('./Master/notification.map.user/notification.map.user.route.js');
const aboutUsRoutes = require('./Master/about-us/about-us.route.js');
const termsConditionRoutes = require('./Master/terms-condition/terms-condition.route.js');
const hyperGuidelinesRoutes = require('./Master/hyper-guidelines/hyper-guidelines.route.js');
const refundCancelPolicyRoutes = require('./Master/refund-cancel-policy/refund-cancel-policy.route.js');
const privacyPolicyRoutes = require('./Master/privacy-policy/privacy-policy.route.js');
const plansPricingRoutes = require('./Master/plans-pricing/plans-pricing.route.js');
const contactMessageRoutes = require('./Master/contact-message/contact-message.route.js');
const faqRoutes = require('./Master/faq/faq.route.js');
const albumsRoutes = require('./Master/album/album.route.js');
const albumShareRoutes = require('./Master/album-share/accept_share.routes.js');
const albumShareShareRoutes = require('./Master/album-share/share.route.js');
const addCardRoutes = require('./Master/add-card/add-card.route.js');
const eventTypeRoutes = require('./Master/event-type/event-type.route.js');
const designerMapPhotographersRoutes = require('./Designer/designer-map-photographers/designer-map-photographers.route.js');
const paymentRoutes = require('./Master/payment/payment.route.js');
const planMapUserRoutes = require('./Master/plan-map-user/plan-map-user.route.js');
const activityFeedRoutes = require('./Master/activity-feed/activity-feed.route.js');
const designerDashboardRoutes = require('./Designer/designer-dashboard/designer-dashboard.route.js');
const photographerDashboardRoutes = require('./Photographers/user/photographer-dashboard.route.js');
const fileUploadRoutes = require('./Master/file-upload/file-upload.route.js');

function routes(app) {
    app.use('/api/photographers/user', PhotographersUserRoutes);
    app.use('/api/photographers/dashboard', photographerDashboardRoutes);
    app.use('/api/designer/user', DesignerUserRoutes);
    app.use('/api/role', roleRoutes);
    app.use('/api/state', stateRoutes);
    app.use('/api/city', cityRoutes);
    app.use('/api/country', countryRoutes);
    app.use('/api/social-media', socialMediaRoutes);
    app.use('/api/notifications', notificationsRoutes);
    app.use('/api/notification-map-user', notificationMapUserRoutes);
    app.use('/api/about-us', aboutUsRoutes);
    app.use('/api/terms-condition', termsConditionRoutes);
    app.use('/api/hyper-guidelines', hyperGuidelinesRoutes);
    app.use('/api/refund-cancel-policy', refundCancelPolicyRoutes);
    app.use('/api/privacy-policy', privacyPolicyRoutes);
    app.use('/api/plans-pricing', plansPricingRoutes);
    app.use('/api/contact-message', contactMessageRoutes);
    app.use('/api/faq', faqRoutes);
    app.use('/api/albums', albumsRoutes);
    app.use('/api/album-share', albumShareRoutes);
    app.use('/albums/share', albumShareShareRoutes);
    app.use('/api/add-card', addCardRoutes);
    app.use('/api/event-type', eventTypeRoutes);
    app.use('/api/designer-map-photographers', designerMapPhotographersRoutes);
    app.use('/api/payment', paymentRoutes);
    app.use('/api/plan-map-user', planMapUserRoutes);
    app.use('/api/activity-feed', activityFeedRoutes);
    app.use('/api/designer-dashboard', designerDashboardRoutes);
    app.use('/api/file-upload', fileUploadRoutes);
}

module.exports = routes;